### ISSUE TITLE
Camille Roux @ Paris et Camille Roux @ Montpellier pointent sur Camille Roux @ Paris

### ISSUE THREAD

**Issue by fsarradin** [brownbaglunch/BrownBagLunch#105]
On ne peut pas accéder à Camille Roux @ Montpellier depuis le menu dans la page http://www.brownbaglunch.fr/baggers.html

**Comment by janosgyerik** [comment]
Seems to be working for me. Is there really an issue?

**Comment by nrichand** [comment]
Not really. The main issue is that a baggers can't be in multiple cities. Camille duplicate this contents in the two cities to bypass the limitation. We should change the model to differentiate the baggers from the cities.

**Comment by janosgyerik** [comment]
Got it. I have an improvement almost ready for this. You can expect a PR tonight ;-)

**Comment by janosgyerik** [comment]
#127 fixes this.
