### ISSUE TITLE
Problème d'envoie de mail sur Ubuntu & Chrome ou Ffox

### ISSUE THREAD

**Issue by nrichand** [brownbaglunch/BrownBagLunch#142]
J'essaie d'envoyer un message via votre site (http://www.brownbaglunch.fr/baggers.html) à David Pilato pour lui proposer de venir faire un BBL dans notre société, mais je ne parviens pas à l'envoyer (ou en tous cas je ne reçois pas d'acquittement par mail).

Je clique sur "Invitez moi chez vous!", je remplis les 4 champs, je clique sur "Envoyer". La pop up disparaît mais la page derrière reste "grisée". En cliquant une fois n'importe où, elle reprend son état normal. Je ne reçois pas de copie du mail.
Je suis sous Ubuntu, et j'ai essayé avec Chrome et Firefox.

**Comment by MichaelBitard** [comment]
Je viens d'essayer et ça fonctionne si j'essaie de m'envoyer une demande de BBL, je suis sous ubuntu 13.10 et avec chrome 31.0.1650.63

**Comment by nrichand** [comment]
Oui c'est bon, j'ai réussi à le reproduire et à vite fixer le problème.
Merci Michael d'avoir validé :)
