### ISSUE TITLE
Home page: le bandeau fixe rogne sur le texte

### ISSUE THREAD

**Issue by ptitfred** [brownbaglunch/BrownBagLunch#19]
![image](https://f.cloud.github.com/assets/346377/171391/aed4162e-7a98-11e2-9d06-06cb77b35c28.png)

Chrome 24 Linux

Pour info, c'est bon si je zoome à 110% ; pb de dimension en pixel sans doute ?

**Comment by linsolas** [comment]
Corrigé suite au refactoring du menu.
