### ISSUE TITLE
Supprimer `paire: true|false` dans les data des baggers

### ISSUE THREAD

**Issue by fsarradin** [brownbaglunch/BrownBagLunch#21]
Ce truc est juste pénible et ne devrait pas apparaître dans les data des baggers. Il devrait être possible de mettre au point un script pour l'attribuer correctement avant de passer dans mustache.

A étudier...

**Comment by ptitfred** [comment]
J'ai un commit pour ça !!

**Comment by nrichand** [comment]
C'était juste un bad hack en attendant mieux, je pensais passer sur handlebars pour virer ça. @ptitfred je suis preneur d'un fix :)

**Comment by fsarradin** [comment]
@nrichand pour le bad hack, j'avais bien compris ;)

@ptitfred pareil si tu as un fix, une amélioration quelconque n'hésite pas ^^

**Comment by ptitfred** [comment]
Faut que je l'adapte au nouveau Hash des baggers
