### ISSUE TITLE
On voit le template mustache au chargement de la page des baggers

### ISSUE THREAD

**Issue by fsarradin** [brownbaglunch/BrownBagLunch#22]
Quand la page `baggers.html` n'est pas dans le cache du navigateur, on voit le template mustache s'afficher quelques instants, avant d'être remplacé par la page finale avec application du template.

**Comment by ptitfred** [comment]
:+1: "on voit ta mustache"

**Comment by fsarradin** [comment]
![](http://i687.photobucket.com/albums/vv239/eyeDEEclaire/beard-moustache-championships.jpg)

**Comment by fsarradin** [comment]
les templates sont mis dans des balises script plutôt que dans le body directement.
