### ISSUE TITLE
Des ID plus longs pour les baggers & page alégée

### ISSUE THREAD

**Issue by fsarradin** [brownbaglunch/BrownBagLunch#23]
Passer de `fsa` à `fsarradin` ou `francois.sarradin` (selon affinité).

_On peut privilégier le compte Twitter ?_

**Comment by nrichand** [comment]
Bonne idée le compte twitter, j'ai viré le tag pseudo qui ne servait à rien du coup.

**Comment by fsarradin** [comment]
Vu. merci !

**Comment by ptitfred** [comment]
Dans le même genre on pourrait créer des liens vers les speechs proposés à des fins de communication ou pour les gens intéressés.

**Comment by fsarradin** [comment]
Ca risque de faire pas mal de liens. Je pense plutôt à des apperçus.

**Comment by linsolas** [comment]
Est-ce que ça ne vaudrait pas le coup de cacher par défaut la description de chaque présentation, et quand on clique sur la petite flèche, le détail s'ouvre ?
Le souci que j'ai avec cette page, c'est que plus on va avoir de personnes, plus on va avoir une page loooongue.
Je vais faire une page de test pour voir ce que ça donne, ok ?

**Comment by fsarradin** [comment]
En fait, ce qui est nécessaire au niveau de chaque bagger, c'est :
- la photo
- le titre des sessions
- le(s) lieu(x)

Et si on a besoin de plus d'info, on clique dessus.

Avis ?

**Comment by ptitfred** [comment]
Un Bagger badge ?

**Comment by fsarradin** [comment]
Yeah ! Gamification du site :) @nrichand Qu'est-ce que tu fait ?

**Comment by ptitfred** [comment]
Il faut une format de photos cohérent

**Comment by ptitfred** [comment]
Tags/keywords pour les speakers ?

**Comment by nrichand** [comment]
Je suis ok pour réduire les sessions, mais il faut trouver un truc Mobile friendly et assez rapide pour pas que ça deviennent lourd.
Ya ptet la classe Accordion qui peut faire le boulot : http://foundation.zurb.com/docs/elements.php#accEx
Faut qu'on fasse des essais.

**Comment by linsolas** [comment]
Je vous pond un truc dans la journée :)

**Comment by linsolas** [comment]
Hop, voilà une première proposition:

http://www.brownbaglunch.fr/baggers-test

J'ai pas encore regardé sur mobile, je checke après manger.

**Comment by nrichand** [comment]
J'ai réouvert l'issue du coup.
C'est pas mal, je laisserai la bio visible par contre. Chaque clic à un coup pour l'utilisateur, faut trouver le juste milieu.

**Comment by linsolas** [comment]
J'ai changé. La bio est du coup toujours visible. Les descriptions sont "refermables" aussi.

**Comment by linsolas** [comment]
Je pense que la partie "ID" est close, maintenant, non ?
