### ISSUE TITLE
Site cassé

### ISSUE THREAD

**Issue by donaminos** [brownbaglunch/BrownBagLunch#245]
Le site est cassé niveau style et navigation, notamment la page http://www.brownbaglunch.fr/baggers.html

**Comment by linsolas** [comment]
Bonjour.
Pour moi cela fonctionne. Quel navigateur est utilisé ?

**Comment by donaminos** [comment]
Bonjour,

J'utilise chrome version 37.0.2062.103 m. Dans la console j'ai des erreurs 503 sur le CDN cloudflare.

![capture](https://cloud.githubusercontent.com/assets/5103153/4198748/0e1c33a0-37fd-11e4-9bf8-f0110e460312.PNG)

![console](https://cloud.githubusercontent.com/assets/5103153/4198781/884eb36e-37fd-11e4-8d5d-649c2049cb82.PNG)

**Comment by linsolas** [comment]
Hum, c'est visiblement un problème de proxy d'entreprise qui refuse l'accès à Cloudflare.
Une solution serait de rappatrier ces ressources directement sur le site...

**Comment by donaminos** [comment]
D'accord, je ferme le ticket dans ce cas là. Merci pour ta réponse.
