### ISSUE TITLE
La bulle dans la carte des BBL est un peu foireuse.

### ISSUE THREAD

**Issue by linsolas** [brownbaglunch/BrownBagLunch#26]
Problème sur Chrome, Firefox et Safari.

Voir la doc du plugin ici : http://code.google.com/p/jquery-ui-map/

**Comment by abelards** [comment]
Je ne vois pas de bulle à proprement parler, par contre je vois un lien qui se fait mal.
(ex: ajoute l'anchor #Paris puis enchaîne sans changer la page #Paris#Montpellier#Toulouse#Lille#Lille)

Corrigé dans ma PR avec plein de micro-fixes :
https://github.com/abelards/BrownBagLunch/blob/gh-pages/js/baggersUtils.js#L18
