### ISSUE TITLE
Can not send mail

### ISSUE THREAD

**Issue by obazoud** [brownbaglunch/BrownBagLunch#330]
I cannot invite someone, mail form failed.

![screenshot from 2016-02-01 13-40-04](https://cloud.githubusercontent.com/assets/300753/12717669/9570aa24-c8e9-11e5-803f-0978c19858c2.png)

**Comment by nrichand** [comment]
Ok, c'est le backend nodejs qui ne marchait plus. Je l'ai porté sur Heroku, maintenant il refonctionne. A voir si on peut le merger avec le webhook de @dadoonet ou pas.

**Comment by dadoonet** [comment]
bah oui. On est maintenant hébergé par Clever... Le code est dispo somewhere?

**Comment by nrichand** [comment]
ici : https://github.com/nrichand/BrownBagLunch-backend

**Comment by nrichand** [comment]
Si t'a d'autres idées pour faire mieux ou plus simple je suis partant
