### ISSUE TITLE
Refactoring page des baggers

### ISSUE THREAD

**Issue by linsolas** [brownbaglunch/BrownBagLunch#341]
Hello la communauté,

Voulant me mettre à tester un peu VueJS, je me suis dit que je pourrais rendre ça utile en refactorant un peu la page des baggers.
Ma PR n'est pas encore prête, j'ai encore des choses à régler.

Voici une première capture d'écran :

![image](https://cloud.githubusercontent.com/assets/623217/24580828/bd6bdfba-170f-11e7-9121-305220ebaa50.png)

J'ai essayé d'épurer un peu les "cartes", j'ai ajouté un champ de recherche dans la barre.

J'ai encore un peu de boulot :

- [x] ajouter des images (en Creative Commons) pour chaque ville
- [x] remettre la modale de contact
- [ ] voir si je remets la carte Google Maps (pas sûr de l'utilité ?)
- [x] tester a minima le responsive
- [ ] réussir à mettre une image par défaut pour le bagger qui n'en a pas (ou qui ne charge pas)
- [ ] gérer les baggers multi-villes (en particulier sur le header de sa carte)

Vos suggestions et idées sont les bienvenues.

Techniquement parlant, y a un peu de VueJS et du Bootstrap v4. Et du HTML, forcément :)

J'espère pouvoir envoyer ma PR d'ici la semaine prochaine (je ne promet rien, j'ai entendu dire que Devoxx France approchait à grand pas ;) )

**Comment by dadoonet** [comment]
Excellent !

Si j'arrivais à trouver un peu de temps, je pourrais réactiver le webhook pour qu'on puisse intégrer elasticsearch dedans.
Du coup recherche par proximité ou genre, pas texte (y compris fautes de frappe...)

Peut être qu'on peut se trouver un moment à Devoxx ???

**Comment by linsolas** [comment]
pas le jeudi, vu que j'ai mes 2 présentations ce jour-là, mais sinon ok

**Comment by dadoonet** [comment]
Ce qui serait top (j'sais pas si c'est possible) ce serait de pouvoir déployer une branche sous staging.brownbaglunch.fr de façon à pouvoir jouer avec.

**Comment by linsolas** [comment]
ou plus simple : mettre ma page sur `baggers-beta.html` plutôt que `baggers.html`, comme ça on peut accéder à la nouvelle version sans toucher à l'actuelle

**Comment by linsolas** [comment]
closed by #342

**Comment by MichaelBitard** [comment]
Au pire prenez un slot au hackergarten non ?

On Sat, Apr 1, 2017, 22:58 Romain Linsolas <notifications@github.com> wrote:

pas le jeudi, vu que j'ai mes 2 présentations ce jour-là, mais sinon ok

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/brownbaglunch/BrownBagLunch/issues/341#issuecomment-290946794>,
or mute the thread
