### ISSUE TITLE
Enlever les liens absolus

### ISSUE THREAD

**Issue by divarvel** [brownbaglunch/BrownBagLunch#45]
Le fait que tous les liens soient en dur rend le test en local un peu compliqué.

**Comment by nrichand** [comment]
Salut Clément et bienvenu,

Peux tu détailler ton problème?

**Comment by divarvel** [comment]
Avant de submit ma PR, j'ai voulu tester le site en local pour vérifier que je n'avais rien cassé.
Le problème c'est que tous les liens de l'index ont le nom de domaine en dur, ce qui casse la navigation.

**Comment by nrichand** [comment]
Tu veux parler des liens : http://www.brownbaglunch.fr/baggers et locations?
Tu peux pousser ta PR pour ça.

**Comment by linsolas** [comment]
PR acceptée, donc clozed ?
