### ISSUE TITLE
La photo de Mathilde ne passe pas certains proxies

### ISSUE THREAD

**Issue by fsarradin** [brownbaglunch/BrownBagLunch#5]

**Comment by nrichand** [comment]
Est-ce la photo qui ne passe pas le proxy ou bien est-ce le proxy du client pour qui tu travailles qui serait 'un poil' restrictif? :)

**Comment by MathildeLemee** [comment]
C'est directement de twitter, donc je suppose que c'est le proxy qui filtre.

---

 De : nrichand notifications@github.com
À : nrichand/BrownBagLunch BrownBagLunch@noreply.github.com 
Cc : MathildeLemee mathilde.lemee@yahoo.fr 
Envoyé le : Mardi 12 février 2013 22h40
Objet : Re: [BrownBagLunch] La photo de Mathilde ne passe pas certains proxies (#5)

Est-ce la photo qui ne passe pas le proxy ou bien est-ce le proxy du client pour qui tu travailles qui serait 'un poil' restrictif? :)

**Comment by fsarradin** [comment]
+1 pour le proxy parano du client (une grosse banque) ;)

En fait, l'effet au final est un peu bizarre : tout le monde à sa photo, sauf Mathilde. C'est dommage !

Du coup, soit on passe par un site comme gravatar, soit on embarque les photos dans le repo github.

**Comment by nrichand** [comment]
Je la met sur Github. Ca serait dommage de pas avoir la super photo hopwork de madame ;)
