### ISSUE TITLE
Site en carafe ?

### ISSUE THREAD

**Issue by hlassiege** [brownbaglunch/BrownBagLunch#50]
Quand on clique sur le lien "Trouver un bagger" on tombe sur une 404
Vous êtes au courant ?

**Comment by fsarradin** [comment]
Je n'ai pas le problème !?

D'autres ont essayé ?

**Comment by hlassiege** [comment]
effectivement je pige pas, avec chrome sur l'onglet réseau je me tape une 404 sur cette ressource 

http://nrichand.github.com/

Request URL:http://nrichand.github.com/baggers.html
Request Method:GET
Status Code:404 Not Found
Request Headersview source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Charset:ISO-8859-1,utf-8;q=0.7,*;q=0.3
Accept-Encoding:gzip,deflate,sdch
Accept-Language:fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
DNT:1
Host:nrichand.github.com
Referer:http://nrichand.github.com/BrownBagLunch/
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.97 Safari/537.22
Response Headersview source
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/html
Date:Sat, 09 Mar 2013 10:11:32 GMT
Server:GitHub.com
Transfer-Encoding:chunked

**Comment by hlassiege** [comment]
d'ailleurs effectivement, j'ai une 404 sur le site lui-même http://nrichand.github.com/

**Comment by fsarradin** [comment]
J'ai Chrome. Voici mes tests :

```
http://nrichand.github.com/ => 404
http://nrichand.github.com/BrownBagLunch/ => OK
http://nrichand.github.com/baggers.html => 404
http://www.brownbaglunch.fr/ => OK
http://www.brownbaglunch.fr/baggers.html => OK
```

**Comment by hlassiege** [comment]
ok donc en fait pour moi ca ne marche plus depuis ce commit : 

d25b8ffbd473cce4819ff3d195f0695f23b14383

**Comment by ptitfred** [comment]
oh ironie.

2013/3/9 hlassiege notifications@github.com

> ok donc en fait pour moi ca ne marche plus depuis ce commit :
> 
> d25b8ffhttps://github.com/nrichand/BrownBagLunch/commit/d25b8ffbd473cce4819ff3d195f0695f23b14383
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nrichand/BrownBagLunch/issues/50#issuecomment-14660968
> .

## 

Frédéric Menou

**Comment by nrichand** [comment]
En fait le problème vient du fait que tu y accède depuis http://nrichand.github.com/BrownBagLunch/ au lieu de www.brownbaglunch.fr

Je pense que le CNAME est capout car il devrait remapper http://nrichand.github.com/BrownBagLunch/ :/

**Comment by hlassiege** [comment]
en fait j'y accédais depuis :

http://bagger.brownbaglunch.fr/

mais effectivement depuis www.brownbaglunch.fr ca marche

**Comment by nrichand** [comment]
Mince, d'ou tu tire http://bagger.brownbaglunch.fr/ ? J'avais une vieille redirection qui trainait sur Gandi que j'avais fais au début, je l'ai reconfé pour éviter ce problème.

**Comment by hlassiege** [comment]
un jour j'ai eu cette adresse, depuis je tape juste "b" sur chrome et je
fais mon faineant, c'est le premier choix ^^

**Comment by fsarradin** [comment]
Pour le coup, la touche [Suppr] est ton amie :/

Ceci dit, http://bagger.brownbaglunch.fr/ fonctionne chez moi.

**Comment by linsolas** [comment]
On va dire que c'est clos ?
