### ISSUE TITLE
La liste des baggers et la carte ne s'affiche pas sous Chrome

### ISSUE THREAD

**Issue by fsarradin** [brownbaglunch/BrownBagLunch#64]
La page qui ne s'affiche pas correctement : http://www.brownbaglunch.fr/baggers

![capture-page_baggers-chrome_canary](https://f.cloud.github.com/assets/395048/506281/68b0900c-bd49-11e2-91f2-8e742c409cb0.png)

Version utilisée : "Version 29.0.1507.2 canary SyzyASan"

Sinon, ça marche bien sous Chrome de base.

EDIT 2013-05-24 : reproduit en version 27 (dernier update de la version de base de Chrome)

**Comment by nrichand** [comment]
Le bug n'est-il pas plutôt à ouvrir coté Chrome Canary? ;)

**Comment by fsarradin** [comment]
C'est en cours... :)

**Comment by fsarradin** [comment]
Voici ce que me dit la console Chrome :

```
> Refused to execute script from 'https://raw.github.com/HPNeo/gmaps/master/gmaps.js'
  because its MIME type ('text/plain') is not executable, and strict MIME type checking is
  enabled. (baggers.html:1)
> Uncaught ReferenceError: GMaps is not defined  (baggersUtils.js:3)
```

Le problème est que `gmaps.js` est récupéré avec le type MIME `text/plain` et non avec le type MIME `text/javascript`. Ceci est du au service `https://raw.github.com/` qui envoie tout en plain text, indépendamment du contenu.

Pour résoudre le problème il faut soit récupérer le fichier et l'intégrer dans l'arborescence, soit passer par le service `https://rawgithub.com/`.

Référence : https://rawgithub.com/

**Comment by fsarradin** [comment]
Fonctionne en passant par https://rawgithub.com/

Commit: https://github.com/nrichand/BrownBagLunch/commit/31b0e7b6d8c0b2f65d1fca9006eb6f706d903e1c
