### ISSUE TITLE
Ajout d'un bouton "Luncher avec ..."

### ISSUE THREAD

**Issue by bmoitie** [brownbaglunch/BrownBagLunch#67]
On ajoute un bon bouton devant chaque bagger permettant aux personnes intéressées de cliquer dessus pour l'envoie de mail (avec en copie bagger dictateur).

**Comment by nrichand** [comment]
J'ai déjà fait le début en mettant un bouton. Je réfléchis pour la suite.

**Comment by linsolas** [comment]
C'est fait maintenant.
