### ISSUE TITLE
Liste baggers sous IE

### ISSUE THREAD

**Issue by Ouarzy** [brownbaglunch/BrownBagLunch#71]
La liste baggers sous ie ne marche pas

**Comment by fsarradin** [comment]
Est-ce que l'affichage est équivalent à celui de l'[issue #64](https://github.com/nrichand/BrownBagLunch/issues/64) ?

**Comment by fsarradin** [comment]
@Ouarzy : j'ai fait des corrections. Peux-tu réessayer sous IE ?

**Comment by Ouarzy** [comment]
Désolé du temps de réaction. Oui super ça fonctionne en tout cas sous ie 10 :)
