### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by abelards** [brownbaglunch/BrownBagLunch#86]
Bonjour,
GitHub a ajouté les licences, c'est vrai que pour un site public c'est important.
Je propose la CC-By-SA, telle que vous pouvez la voir ici :
https://github.com/simonc/iwanttolearnruby/pull/8/files
Qu'en pensez-vous ?

**Comment by fsarradin** [comment]
Je vote pour :) :+1:

**Comment by nrichand** [comment]
Pareil, @abelards tu fais la PR ou tu veux qu'on le fasse?
Merci beaucoup

**Comment by fsarradin** [comment]
@nrichand et si tu lui donnais les droits ? Ca permettrait d'aller plus vite :)

**Comment by nrichand** [comment]
@fsarradin j'étais en train de le faire :)
